---
title: An R Markdown document converted from "Reasoning with Data - Chapter 6.ipynb"
output: html_document
---

```{r}
set.seed(1)
pgrp1 <- sample(precip,20, replace=TRUE)
pgrp2 <- sample(precip,20, replace=TRUE)
pgrp3 <- sample(precip,20, replace=TRUE)

var(c(pgrp1,pgrp2,pgrp3))
var(precip)
```

```{r}
# Preparing for the third bar plot below
v1 <- var(precip)
v2 <- var(c(pgrp1,pgrp2,pgrp3))
```

```{r}
mean(pgrp1) # Examine the means of the three groups
mean(pgrp2)
mean(pgrp3)
library(repr)
options(repr.plot.width=4, repr.plot.height=4)
barplot(c(mean(pgrp1),mean(pgrp2),mean(pgrp3))) # Create a bar plot of the means
```

```{r}
var(c(mean(pgrp1),mean(pgrp2),mean(pgrp3)))     # Variance among the means
```

```{r}
barplot(c(mean(pgrp1),mean(pgrp2),mean(pgrp3)), main=NULL) # Bar plot of the new means
```

```{r}
var(c(mean(pgrp1),mean(pgrp2),mean(pgrp3)))
var(c(pgrp1,pgrp2,pgrp3))
```

```{r}
# v1 and v2 were defined above
v3 <- var(c(pgrp1,pgrp2,pgrp3))

barplot(c(v1,v2,v3),names.arg=c("Original Data","3 Samples","3rd Grp+5"),cex.names=0.75)
```

```{r}
randomFs <- rf(n=100,df1=2,df2=57)
hist(randomFs, main=NULL)
```

```{r}
# Run ANOVA on groups sampled from the same population
set.seed(10)   # Control the randomization
precipAmount <- sample(precip,60,replace=TRUE)  # Enough for 3 groups of 20
precipGrp <- as.factor(rep(seq(from=1,to=3,by=1),20)) # Group designators, 3 groups
precipDF <- data.frame(precipAmount, precipGrp)  # Put everything in data frame
boxplot(precipAmount ~ precipGrp, data=precipDF, main=NULL) # Get a box plot of the distribs
```

```{r}
precipOut <- aov(precipAmount ~ precipGrp, data=precipDF) # Run the ANOVA
summary(precipOut) # Provide an ANOVA table
```

```{r}
# Uses the density function to show the shape of different F-distributions
fVals <- seq(from=0.01,to=5,by=0.01)
plot(fVals,df(fVals,df1=2,df2=57), col="black")
points(fVals,df(fVals,df1=3,df2=57), col="blue")
points(fVals,df(fVals,df1=4,df2=57), col="green")
```

```{r}
hist(precipOut$residuals)  # Summarize the residuals
```

```{r}
# This is the code for Sidebar 6.1
# install.packages('gtools') #install gtools to get permutations; already installed on Azure Notebooks
library(gtools) # Make the package ready
tinyPop <- c(1,2,3) # Here is a tiny population
allSamp <- permutations(n=3,r=3,v=tinyPop,repeats.allowed=T)
allSamp # Verify: 27 unique samples
apply(allSamp,1,var) # List the sample variance of each sample
barplot(apply(allSamp,1,var)) # What is the mean of those variances
abline(h=0.6667)
mean(apply(allSamp,1,var)) # What is the mean of those variances
```

```{r}
# Code for sidebar 6.2
install.packages("BEST")
library(BEST)
data(mtcars)
priorList <- list(muM = c(20,20), muSD = c(4,4))
carsBest2 <- BESTmcmc(mtcars$mpg[mtcars$am==0] ,mtcars$mpg[mtcars$am==1],priors=priorList) 
plot(carsBest2, main=NULL) 
```

```{r}
# Code for Bayesian ANOVA
install.packages("BayesFactor") 
library("BayesFactor") 


precipBayesOut <- anovaBF(precipAmount ~ precipGrp, data=precipDF) # Calc Bayes Factors
mcmcOut <- posterior(precipBayesOut,iterations=10000)  # Run mcmc iterations
plot(mcmcOut[,"mu"], main=NULL) # Show the range of values for the grand mean
```

```{r}
# Display a 95% HDI for precipitation group 1
par(mfcol=c(1,1))
hist(mcmcOut[,"precipGrp-1"], main=NULL)
abline(v=quantile(mcmcOut[,"precipGrp-1"],c(0.025)), col="black")
abline(v=quantile(mcmcOut[,"precipGrp-1"],c(0.975)), col="black")
```

```{r}
# Give the boundaries of the 95% HDI for precipitation group 1
print("95% HDI lower bound: ") 
print(quantile(mcmcOut[,"precipGrp-1"],c(0.025)))
print("95% HDI upper bound: ") 
print(quantile(mcmcOut[,"precipGrp-1"],c(0.975)))
```

```{r}
boxplot(as.matrix(mcmcOut[,2:4]), main=NULL) # Boxplot the posteriors for the groups
```

```{r}
summary(mcmcOut)
# Uncomment to show the other groups
# plot(mcmcOut[,"precipGrp-2"])  # Show the range of values for the second group
# plot(mcmcOut[,"precipGrp-3"])  # Show the range of values for the third group
```

```{r}
# Examine the output object
precipBayesOut
```

```{r}
# Analyze chickwt data that contains multiple groups with some mean differences
data(chickwts)
chicksOut <- aov(weight ~ feed, data=chickwts) # Run the ANOVA
summary(chicksOut)
```

```{r}
chicksBayesOut <- anovaBF(weight ~ feed, data=chickwts) # Calc Bayes Factors
mcmcOut2 <- posterior(chicksBayesOut,iterations=10000)  # Run mcmc iterations
par(mar=c(7,4,4,2),las=2) # Make a little more room for the labels
boxplot(as.matrix(mcmcOut2[,2:7]), main=NULL) # Boxplot the posteriors for the groups
par(mar=c(5,4,4,2),las=0) 
```

```{r}
summary(mcmcOut2)
```

```{r}
# Sample post hoc comparison of sunflower and meatmeal
install.packages("BEST")
library(BEST)
plot(BESTmcmc(chickwts[chickwts$feed=="sunflower",1],chickwts[chickwts$feed=="meatmeal",1]))
```

```{r}
chicksBayesOut
```

```{r}

```

