---
title: An R Markdown document converted from "Reasoning with Data - Chapter 3.ipynb"
output: html_document
---

```{r}
toastAngleData <- runif(1000,0,180) # Random numbers from uniform distribution
head(toastAngleData) # Look at the first few numbers in the list
tail(toastAngleData) # Look at the last few numbers in the list
hist(toastAngleData) # Plot a histogram of all 1000 data points
```

```{r}
sample(toastAngleData,size=14,replace=TRUE)

mean(sample(toastAngleData,size=14,replace=TRUE))

replicate(4, mean(sample(toastAngleData,size=14,replace=TRUE)))

samplingDistribution <- replicate(10000,mean(sample(toastAngleData,size=14,replace=TRUE)))
hist(samplingDistribution, main=NULL)
```

```{r}
mean(samplingDistribution)
mean(toastAngleData)

summary(samplingDistribution)

quantile(samplingDistribution, c(.01, .05,  .50, .95, .99))
```

```{r}
hist(samplingDistribution, main=NULL)
abline(v=quantile(samplingDistribution,.01))
abline(v=quantile(samplingDistribution,.05))
abline(v=quantile(samplingDistribution,.95))
abline(v=quantile(samplingDistribution,.99))
```

```{r}
samplingDistribution[ samplingDistribution <= quantile(samplingDistribution,.01) ]

summary( samplingDistribution[samplingDistribution <= quantile(samplingDistribution,.01)] )
```

```{r}

```

